[package]
name = "ler-maker"
version = "0.1.0"
authors = ["Xifire"]
description = ""
license = "MIT"
repository = ""
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
resvg = "0.35.0"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.22.1"
